### PR TITLE
fix(types/mutation): pattern matching for result variants

### LINKED ISSUE #81: Pattern matching for a mutation result is not correct
**Issue Labels**
- [x] has-reproduction
- [x] bug
- [x] blocking

I noticed that the pattern matching for the mutation result is not quite correct.

https://github.com/apollographql/reason-apollo/blob/master/src/graphql-types/ReasonApolloMutation.re#L63-L67

```reason
switch (
  apolloData##called |> Js.to_bool,
  apolloData##loading |> Js.to_bool,
  apolloData##data |> ReasonApolloUtils.getNonEmptyObj,
  apolloData##error |> Js.Nullable.to_opt
) {
| (true, false, _, _) => Called
| (_, true, _, _) => Loading
| (false, false, Some(data), None) => Data(Config.parse(data))
| (false, false, _, Some(error)) => Error(error)
| (false, false, None, None) => NoData
```

#### Mutation execution flow
https://github.com/apollographql/react-apollo/blob/master/src/Mutation.tsx#L165-L179

The initial `state` is 

```js
{
  loading: false,
  called: false,
  error: undefined,
  data: undefined,
}
```

When the mutation is being executed, the state transitions first to: (`onStartMutation`)

```js
{
  loading: true,
  called: true,
  error: undefined,
  data: undefined,
}
```

Then we have either `onCompletedMutation` or `onMutationError`. In both cases the `loading` is set to `false` and either `data` or `error` are filled up.

⚠️ **However, `called` still remains to `true`**

#### Pattern matching problem

So if we look at the pattern matching, we clearly see that `Data`, `Error` and `NoData` assume `called` to be `false`, which is wrong. Additionally, a variant for the "initial" state is also missing in my opinion.

#### Proposed solution

We should add a new variant called e.g. `NoCalled` (which reflects the initial state). The pattern matching should be then fixed as following:

```reason
| (false, false, _, _) => NotCalled
| (true, false, Some(data), _) => Data(Config.parse(data))
| (true, false, _, Some(error)) => Error(error)
| (true, false, None, None) => NoData
| (true, _, _, _) => Called
| (_, true, _, _) => Loading
```

### PR DESCRIPTION
**Pull request by emmenko**
**Pull Request Labels**
- [x] bug
- [x] blocking

Fixes #81 

Optional TODOs:
- [ ] update examples by using mutation results with pattern matching
- [ ] test `apolloDataToReason` function

### CODE REVIEW

**Comment by emmenko** [comment]
@Gregoirevda hi, have you had the chance to look at this? How should we proceed here? 😇

**Comment by ng-marcus** [comment]
I see the same issue, where my mutation result gets stuck on Called due to the pattern matching issue, and it looks like this fix resolves the problem.

**Comment by Gregoirevda** [comment]
Thanks for this PR @emmenko and sorry for taking so much time!
When you look at the `called` prop: https://github.com/apollographql/react-apollo/pull/1775
And the reason why it has been added: https://github.com/apollographql/react-apollo/issues/1773

It's only there to represent the notCalled state instead of an empty response for easier destructuring in JS.

It has been discussed in this thread that a variant can't represent all possible states of a GraphQL result, since a GraphQL result can be loading with data and with an error. Which would result in an impossible set of tags to pattern match on. 
https://github.com/apollographql/reason-apollo/issues/61

I believe we should try to keep the variant as small as possible, handling common usecases. I believe we have to pattern match on all cases, even if it only throw a warning, it's very usefull to know all cases are covered. Therefore, a small variant will ease the full pattern match for everyone.

As you mentionned, initial state is:
```
const initialState = {
  loading: false,
  called: false,
  error: undefined,
  data: undefined,
};
```

Can we represent the result as this variant? 
```
type response =
      | Loading
      | Error(apolloError)
      | Data(Config.t);
```

Would you be blocked by not having a Called/NotCalled?
Called/NotCalled is only usefull for the first time the user triggers the mutation, any subsequent mutations calls will leave the Called/NotCalled as is. (Making them useless I guess)

Notice that I also deleted the `Data` because a mutation 
```
mutation do (
  doSomething {
     id
  }
}
```

Will at least have `data` (if there's no error)
```
{
  doSomething: null 
}
```

**Comment by Gregoirevda** [comment]
Just made a PR to fix the `NoData` tag: https://github.com/apollographql/reason-apollo/pull/86

**Comment by ng-marcus** [comment]
This fix looks good to me,  I don't use called/not called and the smaller variant makes sense.

**Comment by Gregoirevda** [comment]
Merged here: https://github.com/apollographql/reason-apollo/pull/86
And published under `reason-apollo@beta` for now.

**Comment by emmenko** [comment]
Thanks! I also don’t use called. As long as we make it properly work I’m fine with everything 😜

I’ll give the beta release a try tomorrow 🙌

**Comment by ng-marcus** [comment]
I've just tried this, and on first render  I get an Error right away before I call it

{message: "No data", graphQLErrors: null, networkError: null}

I can ignore this and the states then work and I get back the data I created in the mutation, but it's probably not good to have to check the message of the error, or for for the variant to be in error state when it's not really.

**Comment by emmenko** [comment]
I think we still have the problem: https://github.com/apollographql/reason-apollo/pull/86#pullrequestreview-121855255

**Comment by Gregoirevda** [comment]
Should be fixed now under `reason-apollo@beta` (0.9.0) I'll leave this open until confirmation

**Pull request closed without merging**
