### PR TITLE
return mutation error

### PR DESCRIPTION
**Pull request by Gregoirevda**

### CODE REVIEW

**Comment by thangngoc89** [comment]
I think the same thing could be done for Query. Or are we waiting for watchQuery to be merged?

**Comment by Gregoirevda** [comment]
Yep, I'll merge watchQuery as soon as possible

**Comment by patoncrispy** [comment]
Has this been published yet?

**Comment by Gregoirevda** [comment]
just did it

**Comment by patoncrispy** [comment]
Amazing. Thank you, good sir!

**Pull request merged**
