### PR TITLE
Remove (most) type annotations from implementations

### LINKED ISSUE #226: Version compatibility issue with ReasonApolloMutation.re ?
I'm new to reason and reason-apollo so I hope this is not an obvious issue and thanks in advance.

I've followed the read me instructions to the best of my ability but am getting an error: "The module or file ApolloInMemoryCache can't be found."

I generated the project with bsb -init so there is a script and did an npm start.

I've checked my bsconfig.json
"bs-dependencies": ["reason-react", "reason-apollo"],
  "ppx-flags": ["@baransu/graphql_ppx_re/ppx6"],

and package.json

"dependencies": {
    "apollo-utilities": "^1.3.3",
    "react": "^16.8.1",
    "react-dom": "^16.8.1",
    "reason-apollo": "^0.18.0",
    "reason-react": ">=0.7.0"
  },
  "devDependencies": {
    "@baransu/graphql_ppx_re": "^0.6.1",
    "bs-platform": "^7.1.0",
    "moduleserve": "^0.9.0"
  }

I think the whole package is not compiling and when I do an 'npm run build' I get the following error:

We've found a bug for you!
  /Users/julio/projects/BuildStrongConnections/reason-client/node_modules/reason-apollo/src/graphql-types/ReasonApolloMutation.re 133:10-29

  131 ┆ let make =
  132 ┆     (
  133 ┆       ~variables: Js.Json.t=?,
  134 ┆       ~onError: apolloError => unit=?,
  135 ┆       ~onCompleted: unit => unit=?,

  ReasonReact: optional argument annotations must have explicit option. Did you mean option(Js.Json.t)=??

It feels like a version incompatibility / regression. Any tips or ideas appreciated. Thanks in advance.

**Issue Labels**

- [ ] has-reproduction
- [ ] feature
- [ ] docs
- [x] blocking
- [ ] good first issue

### PR DESCRIPTION
**Pull request by yawaramin**
And add interface files. Verified working with bs-platform 7.0.1 and 7.1.0. Also couple of minor tweaks to get rid of shadowing warnings.

Fix #226

### CODE REVIEW

**Comment by bobzhang** [comment]
ping @yawaramin ?

**Comment by yawaramin** [comment]
Hi @bobzhang all good from my end, waiting for review and hopefully merge.

**Comment by kutyel** [comment]
I can confirm that this fixes the problem, otherwise `reason-apollo` is **unusable** with the latest version of bucklescript 😟

**Comment by Gregoirevda** [comment]
I've published this under `0.19.0` on npmjs

**Comment by yawaramin** [comment]
@Gregoirevda awesome :-D thank you for your hard work 👍

**Pull request merged**
